/**
 * Données mock pour le MVP.
 * À remplacer par des fetch Directus quand le CMS sera branché (voir lib/directus.ts — à créer).
 */
import type { Metier, Study, Branche } from "./types";

export const branches: Branche[] = [
  { code: "BANQUE", idcc: "2120", libelle: "Banque", effectifsSalaries: 62000, nbEntreprises: 320 },
  { code: "ASSURANCE", idcc: "1672", libelle: "Assurance", effectifsSalaries: 42000, nbEntreprises: 280 },
  { code: "COURTAGE", idcc: "2247", libelle: "Courtage d'assurance", effectifsSalaries: 28000, nbEntreprises: 4800 },
  { code: "AGENTS", idcc: "2335", libelle: "Agents généraux", effectifsSalaries: 12000, nbEntreprises: 2100 },
  { code: "BE", idcc: "1486", libelle: "Bureaux d'études", effectifsSalaries: 28000, nbEntreprises: 580 },
  { code: "EC", idcc: "787", libelle: "Experts-comptables", effectifsSalaries: 15000, nbEntreprises: 640 },
];

export const metiersTopTrimestre: Metier[] = [
  {
    slug: "technicien-maintenance-industrielle",
    libelle: "Technicien·ne maintenance industrielle",
    codeRome: "I1304",
    famille: { code: "F07", libelle: "Conception & Maintenance", icon: "cog" },
    branches: ["BE"],
    resume:
      "Intervient sur les équipements de production, diagnostique les pannes et planifie la maintenance préventive dans un environnement industriel automatisé.",
    tension: "tension",
    effectifs: 8420,
    salaireMedian: 36.2,
    indiceTension: 2.4,
    nbFormations: 12,
    nbCqp: 3,
    competences: [],
    majLe: "2026-04-12",
  },
  {
    slug: "data-analyst-branches",
    libelle: "Data analyst branches professionnelles",
    codeRome: "M1403",
    famille: { code: "F12", libelle: "Data & Analytics", icon: "bar-chart-3" },
    branches: ["ASSURANCE", "BANQUE"],
    resume:
      "Exploite les données d'emploi et de formation pour éclairer les politiques de branche et produire des tableaux de bord prospectifs.",
    tension: "emergent",
    effectifs: 1200,
    salaireMedian: 42.5,
    indiceTension: 1.3,
    nbFormations: 6,
    nbCqp: 3,
    competences: [],
    majLe: "2026-03-28",
  },
  {
    slug: "responsable-transition-ecologique",
    libelle: "Responsable transition écologique",
    codeRome: "H1302",
    famille: { code: "F18", libelle: "Qualité & RSE", icon: "leaf" },
    branches: ["ASSURANCE", "BE", "BANQUE"],
    resume:
      "Pilote les démarches bas-carbone, accompagne la certification RSE et coordonne l'évolution des compétences environnementales.",
    tension: "prospect",
    effectifs: 3200,
    salaireMedian: 48.0,
    indiceTension: 1.1,
    nbFormations: 8,
    nbCqp: 2,
    competences: [],
    majLe: "2026-04-02",
  },
  {
    slug: "charge-developpement-competences",
    libelle: "Chargé·e de développement des compétences",
    codeRome: "M1502",
    famille: { code: "F15", libelle: "Ressources humaines", icon: "users" },
    branches: ["ASSURANCE", "BANQUE", "COURTAGE"],
    resume:
      "Construit les plans de formation, anime le dialogue social sur les compétences et accompagne les mobilités internes.",
    tension: "stable",
    effectifs: 5600,
    salaireMedian: 44.0,
    indiceTension: 0.9,
    nbFormations: 8,
    nbCqp: 1,
    competences: [],
    majLe: "2026-03-20",
  },
  {
    slug: "technicien-energies-renouvelables",
    libelle: "Technicien·ne énergies renouvelables",
    codeRome: "F1605",
    famille: { code: "F08", libelle: "Énergie & réseaux", icon: "zap" },
    branches: ["BE"],
    resume:
      "Installe, raccorde et maintient les équipements photovoltaïques, éoliens et de stockage d'énergie en milieu industriel et tertiaire.",
    tension: "tension",
    effectifs: 1800,
    salaireMedian: 34.5,
    indiceTension: 2.1,
    nbFormations: 7,
    nbCqp: 2,
    competences: [],
    majLe: "2026-04-08",
  },
  {
    slug: "integrateur-ia-operationnelle",
    libelle: "Intégrateur·trice IA opérationnelle",
    codeRome: "M1805",
    famille: { code: "F21", libelle: "Numérique & IA", icon: "sparkles" },
    branches: ["BE", "BANQUE", "ASSURANCE"],
    resume:
      "Déploie et supervise les outils d'intelligence artificielle dans les process métier, forme les équipes et documente les usages responsables.",
    tension: "emergent",
    effectifs: 850,
    salaireMedian: 52.0,
    indiceTension: 1.8,
    nbFormations: 5,
    nbCqp: 2,
    competences: [],
    majLe: "2026-04-10",
  },
];

export const studiesRecentes: Study[] = [
  {
    id: "26-04",
    numero: "N°26.04",
    title: "Métiers de l'industrie et transition écologique — horizon 2035",
    abstract:
      "Cartographie des évolutions des compétences attendues dans les branches face aux enjeux de décarbonation, d'économie circulaire et d'adaptation climatique.",
    kind: "prospective",
    branche: "Transverse Atlas",
    tags: ["Transition écologique", "Compétences", "2035"],
    datePubli: "2026-04-08",
    coverVariant: "green",
    coverLetter: "P",
    formats: [
      { type: "pdf", label: "PDF", pages: 84 },
      { type: "excel", label: "Excel" },
    ],
  },
  {
    id: "25-11",
    numero: "N°25.11",
    title: "Reconversions professionnelles dans la branche : profils et trajectoires",
    abstract:
      "Analyse quantitative et qualitative des parcours de reconversion observés sur 2020-2025. Facteurs de réussite, freins et dispositifs mobilisés.",
    kind: "enquete",
    branche: "Assurance",
    idcc: "1672",
    tags: ["Reconversion", "Mobilité"],
    datePubli: "2025-11-14",
    coverVariant: "purple",
    coverLetter: "R",
    formats: [
      { type: "pdf", label: "PDF", pages: 52 },
      { type: "excel", label: "Données" },
    ],
  },
  {
    id: "26-t1",
    numero: "T1 2026",
    title: "Baromètre trimestriel de l'emploi et de la formation",
    abstract:
      "Chiffres-clés trimestriels : effectifs, tensions, contrats d'alternance, taux d'accès à la formation, évolution des salaires médians par métier.",
    kind: "barometre",
    branche: "Transverse Atlas",
    tags: ["Baromètre", "Emploi", "Formation"],
    datePubli: "2026-03-28",
    coverVariant: "olive",
    coverLetter: "B",
    formats: [
      { type: "pdf", label: "PDF", pages: 28 },
      { type: "excel", label: "Données T1" },
    ],
  },
];

/** Catalogue complet des études (pour la page /etudes avec filtres). */
export const allStudies: Study[] = [
  ...studiesRecentes,
  {
    id: "26-03",
    numero: "N°26.03",
    title: "Les compétences relationnelles dans la vente d'assurance en 2030",
    abstract:
      "Troisième volet de la série IMAGINE : recomposition du métier commercial face à la digitalisation et à la montée des attentes sociétales des clients.",
    kind: "enquete",
    branche: "Assurance",
    idcc: "1672",
    tags: ["Compétences", "Commercial"],
    datePubli: "2026-03-10",
    coverVariant: "purple",
    coverLetter: "E",
    formats: [{ type: "pdf", label: "PDF", pages: 62 }, { type: "excel", label: "Excel" }],
  },
  {
    id: "26-02",
    numero: "N°26.02",
    title: "IA générative et métiers de service — 26 compétences clés en 2030",
    abstract:
      "Étude conjointe avec Colombus Consulting sur l'impact de l'IA générative dans les branches financières et de conseil.",
    kind: "prospective",
    branche: "Transverse Atlas",
    tags: ["IA", "Compétences"],
    datePubli: "2026-02-22",
    coverVariant: "deep",
    coverLetter: "I",
    formats: [{ type: "pdf", label: "PDF", pages: 104 }, { type: "excel", label: "Excel" }],
  },
  {
    id: "25-10",
    numero: "N°25.10",
    title: "Diagnostic handicap : état des lieux dans la branche assurance",
    abstract:
      "Diagnostic branche cofinancé avec l'Agefiph sur l'emploi des personnes en situation de handicap. Plan d'action et recommandations.",
    kind: "enquete",
    branche: "Assurance",
    idcc: "1672",
    tags: ["Handicap", "Diversité"],
    datePubli: "2025-10-18",
    coverVariant: "green",
    coverLetter: "D",
    formats: [{ type: "pdf", label: "PDF", pages: 48 }, { type: "synthese", label: "Synthèse" }],
  },
  {
    id: "25-09",
    numero: "N°25.09",
    title: "Cybersécurité dans les services financiers : compétences 2025-2028",
    abstract:
      "Cadrage Atlas adossé à l'étude OPIIEC. Quatre familles métiers identifiées : détection, audit, pilotage, conception.",
    kind: "prospective",
    branche: "Transverse Atlas",
    tags: ["Cybersécurité", "IA"],
    datePubli: "2025-09-05",
    coverVariant: "purple",
    coverLetter: "C",
    formats: [{ type: "pdf", label: "PDF", pages: 72 }, { type: "excel", label: "Excel" }],
  },
  {
    id: "25-07",
    numero: "N°25.07",
    title: "Les compétences clés des actuaires en 2030",
    abstract:
      "Évolution du métier d'actuaire avec la montée en puissance des data sciences, du climate risk et de l'actuariat non-vie personnalisé.",
    kind: "enquete",
    branche: "Assurance",
    idcc: "1672",
    tags: ["Compétences", "Data"],
    datePubli: "2025-07-12",
    coverVariant: "olive",
    coverLetter: "A",
    formats: [{ type: "pdf", label: "PDF", pages: 68 }, { type: "excel", label: "Excel" }],
  },
  {
    id: "25-05",
    numero: "N°25.05",
    title: "Les jeunes diplômés et l'assurance : baromètre d'attractivité 2025",
    abstract:
      "Enquête auprès de 2 400 étudiants sur la perception du secteur de l'assurance comme employeur. Freins, leviers, recommandations branche.",
    kind: "enquete",
    branche: "Assurance",
    idcc: "1672",
    tags: ["Attractivité", "Démographie"],
    datePubli: "2025-05-20",
    coverVariant: "deep",
    coverLetter: "J",
    formats: [{ type: "pdf", label: "PDF", pages: 40 }, { type: "excel", label: "Excel" }],
  },
  {
    id: "25-03",
    numero: "N°25.03",
    title: "Manager de proximité en assurance : transformation du rôle à horizon 2028",
    abstract:
      "Évolution du management intermédiaire face au travail hybride, à l'automatisation et aux enjeux RSE.",
    kind: "prospective",
    branche: "Assurance",
    idcc: "1672",
    tags: ["Management", "RSE"],
    datePubli: "2025-03-14",
    coverVariant: "green",
    coverLetter: "M",
    formats: [{ type: "pdf", label: "PDF", pages: 58 }, { type: "synthese", label: "Synthèse" }],
  },
  {
    id: "25-02",
    numero: "N°25.02",
    title: "Cartographie des métiers des bureaux d'études",
    abstract:
      "Cartographie interbranche des bureaux d'études, ingénierie, conseil, numérique et événementiel.",
    kind: "cartographie",
    branche: "Bureaux d'études",
    idcc: "1486",
    tags: ["Cartographie"],
    datePubli: "2025-02-08",
    coverVariant: "purple",
    coverLetter: "C",
    formats: [{ type: "pdf", label: "PDF", pages: 96 }, { type: "excel", label: "Excel" }, { type: "csv", label: "CSV" }],
  },
];

export const heroStats = [
  { label: "Branches couvertes", value: "11" },
  { label: "Salariés dans le périmètre", value: "187K" },
  { label: "Fiches métiers vivantes", value: "84" },
  { label: "Études publiées", value: "36" },
];
